language: python

python:
  - '2.7'

env: DB_NAME='travis_ci_test' DJANGO_SETTINGS_MODULE='settings' PYTHONPATH=$HOME/build/geodesign/django-wms

#virtualenv:
#  system_site_packages: true

notifications:
  email: false

before_script:
  - psql -c 'CREATE DATABASE travis_ci_test' -U postgres
  - psql -c 'CREATE EXTENSION postgis' -U postgres -d travis_ci_test

install: 
  - sudo rm /etc/apt/sources.list.d/ubuntugis-stable-source.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-mapscript python-gdal gdal-bin binutils
  - ln -s /usr/lib/python2.7/dist-packages/osgeo ~/virtualenv/python2.7/lib/python2.7/site-packages/
  - ln -s /usr/lib/python2.7/dist-packages/GDAL-1.7.3.egg-info ~/virtualenv/python2.7/lib/python2.7/site-packages/
  - ln -s /usr/lib/python2.7/dist-packages/mapscript.py ~/virtualenv/python2.7/lib/python2.7/site-packages/mapscript.py
  - ln -s /usr/lib/python2.7/dist-packages/_mapscript.so ~/virtualenv/python2.7/lib/python2.7/site-packages/_mapscript.so
  - pip install psycopg2==2.5.3 django==1.7
  - pip install --no-deps django-raster==0.1.0

script: django-admin.py test wms
