sudo: required

dist: trusty

language: python

python:
  - '2.7'

env:
  - DB_NAME=raster_aggregation_test PYTHONPATH=$PYTHONPATH:$PWD:/usr/lib/python2.7/dist-packages DJANGO_SETTINGS_MODULE=settings

before_install:
  - psql -c 'create database wms_test;' -U postgres
  - psql -d wms_test -c 'create extension postgis;' -U postgres

install:
  - sudo apt-get -y install python-mapscript
  - pip install Django==1.9.5
  - pip install psycopg2==2.5.3
  - pip install Pillow==2.7.0
  - pip install flake8==2.5.4
  - pip install isort==4.2.5
  - pip install git+https://github.com/geodesign/django-raster.git@master

script: django-admin.py test

notifications:
  email: false
