language: python

python:
  - '2.7'

# addons:
#   postgresql: '9.3'

env: DB_NAME='travis_ci_test' DJANGO_SETTINGS_MODULE='settings' PYTHONPATH=$HOME/build/geodesign/django-wms

notifications:
  email: false

virtualenv:
  system_site_packages: true

before_script:
  - psql -c 'CREATE DATABASE travis_ci_test' -U postgres
  - psql -c 'CREATE EXTENSION postgis' -U postgres -d travis_ci_test

install: 
  - sudo rm /etc/apt/sources.list.d/ubuntugis-stable-source.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-gdal gdal-bin binutils python-mapscript mapserver-bin
  - pip install psycopg2==2.5.3 django==1.7
  - pip install --no-deps django-raster==0.1.0

script: django-admin.py test wms
