language: python

python:
  - '2.7'

addons:
  postgresql: '9.3'

env: DB_NAME='travis_ci_test' DJANGO_SETTINGS_MODULE='settings' PYTHONPATH=$HOME/build/geodesign/django-wms

notifications:
  email: false

virtualenv:
  system_site_packages: true

before_script:
  - psql -c 'CREATE DATABASE travis_ci_test' -U postgres
  - psql -c 'CREATE EXTENSION postgis' -U postgres -d travis_ci_test

install: 
  - echo 'deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu precise main' | sudo tee -a /etc/apt/sources.list
  - echo 'deb-src http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu precise main' | sudo tee -a /etc/apt/sources.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 314DF160
  - sudo apt-get update
  - sudo apt-get install -y libmapserver1
  - sudo apt-get install -y -f python-mapscript

script: django-admin.py test wms
